### ISSUE TITLE
Message de sortie incoherent

### ISSUE THREAD

**Issue by nabondance** [MeilleursAgents/JudCoCo#4]
Lorsque le test fail, le message est quand meme "Branch is clean"

![image](https://user-images.githubusercontent.com/32196400/74645136-a76b3300-5177-11ea-84de-5fb8af4b4aa0.png)

Action concernée: https://github.com/MeilleursAgents/MeilleursAgents/pull/5630/checks?check_run_id=450235976

**Comment by ViBiOh** [comment]
This a github feature, please ask JeanMichel Github

**Comment by nabondance** [comment]
SI un jour JeanMichel Github te donne une solution, on est preneur pour nos actions a nous :)
